#updates a new patient activity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "JohnDoe1@gmail.com",
  "address": "123 main street",
  "date_of_birth": "1995-09-09"
}

###